trigger:
    - platform: event
      event_type: telegram_command
      event_data:
        command: '/PauseVideo'
action:
    - service: media_player.media_pause
      entity_id: media_player.cucina
